# Generated by Django 4.1.7 on 2023-03-03 21:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="status",
            new_name="can_loan",
        ),
    ]
