# Generated by Django 4.1.7 on 2023-03-03 21:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loans",
            old_name="loan_devolution",
            new_name="devolution_date",
        ),
    ]
