# Generated by Django 4.1.7 on 2023-03-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0003_rename_loan_devolution_loans_devolution_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="loans",
            old_name="book",
            new_name="book_copy",
        ),
        migrations.AddField(
            model_name="loans",
            name="expiration_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="loans",
            name="devolution_date",
            field=models.DateField(null=True),
        ),
    ]
