# Generated by Django 4.1.7 on 2023-03-07 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0002_alter_bookcopy_book"),
        ("loans", "0004_rename_book_loans_book_copy_loans_expiration_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loans",
            name="book_copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="loans",
                to="books.bookcopy",
            ),
        ),
    ]
