# Generated by Django 4.1.7 on 2023-03-07 13:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("books", "0002_alter_bookcopy_book"),
        ("loans", "0005_alter_loans_book_copy"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="loans",
            new_name="Loan",
        ),
    ]
