# Generated by Django 4.1.7 on 2023-03-07 19:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("loans", "0006_rename_loans_loan"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="loan",
            name="expiration_date",
        ),
    ]
